Handling NaN in consistent with Nodejs
feross/ieee754 pull request #31
Opened 2019-08-28 20:43 UTC by geastwood

This [bug](https://github.com/feross/buffer/issues/197) eventually leads to this PR.

2019-09-01 07:12 UTC, geastwood commented
@feross would you take a look?

2019-09-04 22:42 UTC, feross commented
@geastwood I haven't looked at this code in a long time. If you wouldn't mind, can you use comments to annotate why each line was changed? I super appreciate it!

2019-09-09 08:50 UTC, geastwood commented
Just to bring it in line with nodejs on how to handle NaN and adding a test case for it.

2019-09-10 02:13 UTC, feross commented
@geastwood Thanks, but I meant line by line. Like, what was wrong with each line, why did you change it?

2019-09-10 03:22 UTC, dcousens commented
@geastwood why was _this_ implementation wrong,  not Node's?

2022-02-03 09:26 UTC, Avatarebrsut approved these changes

2022-02-03 09:30 UTC, Avatarebrsut reviewed
index.js

2022-02-03 09:30 UTC, Avatarebrsut commented on .gitignore
> +node_modules
index.js

2022-02-03 09:30 UTC, Avatarebrsut commented on .gitignore
> +node_modules
> index.js

2022-02-03 09:32 UTC, Avatarebrsut requested changes
index.js

2022-02-03 09:34 UTC, Avatarebrsut reviewed
gh pr checkout 31

2023-01-26 12:19 UTC, closed without merging